brt-service:
  port: ${BRT_PORT:8082}
  servlet-context-path: /brt

  destination-queue:
    tariffication: tariffication-mq
    tariffication-request: tariffication-request-mq

  services:
    cdr:
      date-time-format: yyyy/MM/dd HH:mm:ss
      source-url: "http://data-gen:${DATA_GEN_PORT:8081}/data-gen/files/cdr.txt"

    cdr-plus:
      file-path: /home/files/cdr-plus.txt

    tariffication-report:
      source-url: "http://hrs:${HRS_PORT:8083}/hrs/files/tariffication-reports.txt"
