data-gen-service:
  port: ${DATA_GEN_PORT:8081}
  servlet-context-path: /data-gen

  services:
    call-type-generator:
      incoming-call-chance: 0.5
      incoming-call-code: "02"
      outcoming-call-code: "01"

    phone-number-generator:
      existing-chance: 0.7

    date-time-generator:
      format: yyyy/MM/dd HH:mm:ss
      lower-bound: 2023/01/01 00:00:00
      upper-bound: 2023/02/01 00:00:00
      max-duration: 1h

    cdrs-generator:
      cdr-file-path: files/cdr.txt
      count: 100
